title: Irene Bosque
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal site!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hungry-bassi-32d2d9.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Irene Bosque # add your name
author-img: irene-bosque.jpeg # add your photo
about-author: Hi, I'm Irene Bosque! I'm a mechatronic engineer and currently, I'm a master student at TU Delft doing my master thesis in Machine Learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

include:
  - _static

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
